services:
  payload:
    image: oven/bun:1-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/bun/app
      - node_modules:/home/bun/app/node_modules
    working_dir: /home/bun/app/
    command: sh -c "bun install && bun run dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: majangbuku
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  node_modules:
