services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-http://localhost:3001}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ports:
      - "${PORT:-3001}:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-password}@postgres:5432/${DATABASE_NAME:-majangbuku}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-majangbuku}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT:-5435}:5432"

volumes:
  pgdata:
  node_modules:
