version: "3.9"

services:
  app:
    build: .
    container_name: next_payload_app
    restart: always
    ports:
      - "3001:3000" # Host:Container
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: majangbuku
    ports:
      - "5435:5432" # Host 5435, container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
