import { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'

export async function up({ payload, req }: MigrateUpArgs): Promise<void> {
  // --- Seed Book Categories ---
  const bookCategories = [
    { title: 'Fiksi', slug: 'fiksi' },
    { title: 'Puisi', slug: 'puisi' },
    { title: 'Anak', slug: 'anak' },
    { title: 'Non Fiksi', slug: 'non-fiksi' },
    { title: 'Terbitan Berkala', slug: 'terbitan-berkala' },
    { title: 'Berbahasa Inggris', slug: 'berbahasa-inggris' },
  ]

  const categoryMap: Record<string, number> = {}
  for (const cat of bookCategories) {
    const doc = await payload.create({
      collection: 'book-categories',
      data: cat,
      req,
    })
    categoryMap[cat.slug] = doc.id as number
  }

  // --- Seed FAQ ---
  const faqSeed = [
    {
      question: `Apa itu Komunitas Literasi Majang Buku?`,
      answer: `Majang Buku adalah komunitas literasi pertama di Lumajang yang berdiri sejak Februari 2024. Digagas oleh empat pemudi pecinta buku asal Lumajang, komunitas ini hadir untuk meningkatkan budaya membaca di masyarakat dengan cara yang menyenangkan, menumbuhkan, dan berkelanjutan. Kini Majang Buku memiliki ratusan anggota aktif dan menjalankan berbagai program literasi rutin.`,
    },
    {
      question: `Bagaimana cara bergabung dengan Majang Buku?`,
      answer: `Kamu bisa bergabung dengan cara masuk ke grup WhatsApp komunitas Majang Buku melalui link yang tersedia di bio Instagram @majangbuku atau taplink.cc/majangbuku. Jika kamu berada di luar Lumajang, kamu bisa mendaftar program Diam-Diam Baca (DDB) yang dirancang khusus untuk anggota jarak jauh.`,
    },
    {
      question: `Apakah saya harus membayar untuk bergabung atau meminjam buku?`,
      answer: `Tidak. Bergabung dengan komunitas Majang Buku sepenuhnya gratis. Peminjaman buku juga tidak dipungut biaya apapun. Namun kami sangat mengapresiasi siapa saja yang ingin berkontribusi melalui donasi buku atau dukungan kegiatan komunitas.`,
    },
    {
      question: `Bagaimana cara meminjam buku dari Majang Buku?`,
      answer: `Kamu bisa mengecek ketersediaan buku terlebih dahulu melalui katalog koleksi yang tersedia di website ini. Setelah menemukan buku yang ingin dipinjam, isi formulir peminjaman buku yang tersedia di halaman Library. Tim Majang Buku akan menghubungimu untuk mengatur proses pengambilan buku.`,
    },
    {
      question: `Berapa lama batas waktu peminjaman buku?`,
      answer: `Batas waktu peminjaman buku adalah 14 hari (2 minggu) sejak tanggal pengambilan. Jika kamu membutuhkan waktu lebih lama, kamu bisa menghubungi admin untuk melakukan perpanjangan, selama buku tersebut tidak sedang diantre oleh anggota lain.`,
    },
    {
      question: `Apa saja program rutin yang dijalankan Majang Buku?`,
      answer: `Majang Buku memiliki beberapa program rutin, di antaranya: Piknik Buku (lapak baca terbuka di Alun-alun Lumajang setiap Minggu pagi), Diam-Diam Baca / DDB (komunitas baca online untuk anggota luar Lumajang), Parkir Pikir (kegiatan literasi dan kesehatan mental di ruang publik), Ruang Perempuan Bersuara (forum bagi perempuan untuk berbagi lewat buku), Temu Bicara Tulis / Teralis (diskusi dan pelatihan menulis), dan Klub 5 Pagi (kebiasaan membaca di pagi hari).`,
    },
    {
      question: `Di mana basecamp atau lokasi Majang Buku?`,
      answer: `Basecamp Majang Buku berlokasi di Grati, Sumbersuko, Lumajang. Untuk kegiatan Piknik Buku rutin, kami biasanya hadir di Alun-alun Lumajang setiap Minggu pagi saat car free day. Lokasi bisa berubah tergantung event — pantau terus info terbaru di Instagram @majangbuku.`,
    },
    {
      question: `Bagaimana cara mendonasikan buku ke Majang Buku?`,
      answer: `Kami sangat terbuka menerima donasi buku dalam kondisi baik dan layak baca. Kamu bisa menghubungi admin Majang Buku melalui Instagram @majangbuku or lewat grup WhatsApp komunitas untuk mengatur proses pengiriman atau penyerahan buku donasi. Buku yang diterima akan dimasukkan ke katalog koleksi dan tersedia untuk dipinjam oleh seluruh anggota.`,
    },
    {
      question: `Bagaimana cara berkolaborasi atau menjadi media partner Majang Buku?`,
      answer: `Untuk kolaborasi, media partnership, atau sponsorship kegiatan, kamu bisa menghubungi tim Majang Buku melalui direct message di Instagram @majangbuku. Kami terbuka untuk berbagai bentuk kolaborasi yang mendukung semangat literasi di Lumajang.`,
    },
    {
      question: `Apakah Majang Buku membuka kegiatan untuk anak-anak?`,
      answer: `Ya! Majang Buku memiliki program dan koleksi buku khusus anak-anak. Pada kegiatan seperti Piknik Buku and event sosial seperti Lebaran Literasi, kami secara aktif menghadirkan kegiatan literasi yang ramah anak. Orang tua dipersilakan hadir bersama anak-anak dalam setiap kegiatan terbuka komunitas.`,
    },
  ]

  const faqIds: number[] = []
  for (const faq of faqSeed) {
    const doc = await payload.create({
      collection: 'faq',
      data: {
        question: faq.question,
        answer: {
          root: {
            type: 'root',
            format: '',
            indent: 0,
            version: 1,
            direction: 'ltr',
            children: [
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    text: faq.answer,
                    version: 1,
                  },
                ],
              },
            ],
          },
        },
      },
      req,
    })
    faqIds.push(doc.id as number)
  }

  // --- Seed Global Pages ---
  await payload.updateGlobal({
    slug: 'faq-page',
    data: {
      title: 'FAQ',
      subtitle: 'Find your answers for the most asked questions',
      faqs: faqIds,
    },
    req,
  })

  await payload.updateGlobal({
    slug: 'events-page',
    data: {
      title: 'Kegiatan',
      subtitle: 'Daftar kegiatan terbaru yang akan datang',
      image: null,
    },
    req,
  })

  const biographySeed = {
    paragraphs: [
      `Komunitas Literasi Majang Buku lahir dari keresahan empat pemudi asal Lumajang — Rizka Ayu Kartini, Shabila Fandyta, Fitri Maghfirotul Rohmah, dan Rosalia Wulan — yang ingin menemukan teman-teman sehobi membaca buku. Berawal dari kebiasaan berkunjung ke perpustakaan daerah yang sepi pengunjung, mereka menginisiasi lapak baca di Alun-alun Lumajang setiap Minggu pagi berbekal tikar dan koleksi buku pribadi. Kegiatan sederhana itu kemudian diberi nama "Piknik Buku" dan mendapat sambutan hangat dari warga sekitar.`,
      `Komunitas ini resmi berdiri pada Februari 2024 dengan tujuan meningkatkan kesadaran dan kebiasaan membaca buku di kalangan masyarakat Lumajang. Kini Majang Buku telah berkembang menjadi komunitas literasi dengan ratusan anggota dan berbagai program rutin, menjadi wadah bagi siapa saja yang ingin berbagi pengetahuan, pengalaman, and kecintaan terhadap buku. Dengan semangat "Menyenangkan, Menumbuhkan, and Berkelanjutan", Majang Buku terus menghadirkan ruang-ruang literasi yang inklusif and bermakna di Kabupaten Lumajang.`,
    ],
    visi: `Menjadi komunitas literasi yang menyenangkan, menumbuhkan, and berkelanjutan sehingga dapat meningkatkan budaya membaca masyarakat Lumajang.`,
    misi: [
      `Menyelenggarakan kegiatan literasi yang menyenangkan and mudah diakses oleh seluruh lapisan masyarakat Lumajang.`,
      `Menyediakan koleksi buku yang dapat dipinjam and dibaca oleh siapa saja secara gratis.`,
      `Membangun jaringan komunitas baca yang solid and inklusif, baik secara offline maupun online.`,
      `Mendorong lahirnya penulis, pembicara, and pegiat literasi baru dari Lumajang melalui program-program pengembangan diri.`,
      `Berkolaborasi dengan berbagai pihak — individu, komunitas, maupun institusi — untuk memperluas dampak literasi di Kabupaten Lumajang.`,
      `Menjaga keberlanjutan komunitas dengan sistem organisasi yang transparan and bertanggung jawab.`,
    ],
  }

  const bioChildren: any[] = []
  biographySeed.paragraphs.forEach((p) => {
    bioChildren.push({
      type: 'paragraph',
      format: '',
      indent: 0,
      version: 1,
      children: [{ type: 'text', text: p, version: 1 }],
    })
  })

  bioChildren.push({
    type: 'heading',
    tag: 'h2',
    format: '',
    indent: 0,
    version: 1,
    children: [{ type: 'text', text: 'Visi', version: 1 }],
  })

  bioChildren.push({
    type: 'paragraph',
    format: '',
    indent: 0,
    version: 1,
    children: [{ type: 'text', text: biographySeed.visi, version: 1 }],
  })

  bioChildren.push({
    type: 'heading',
    tag: 'h2',
    format: '',
    indent: 0,
    version: 1,
    children: [{ type: 'text', text: 'Misi', version: 1 }],
  })

  const listItems: any[] = biographySeed.misi.map((m) => ({
    type: 'listitem',
    value: 1,
    version: 1,
    children: [{ type: 'text', text: m, version: 1 }],
  }))

  bioChildren.push({
    type: 'list',
    listType: 'bullet',
    version: 1,
    children: listItems,
  })

  await payload.updateGlobal({
    slug: 'biography-page',
    data: {
      title: 'Biography',
      subtitle: 'Tentang Majang Buku',
      image: null,
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          direction: 'ltr',
          children: bioChildren,
        },
      },
    },
    req,
  })

  // --- Seed Events ---
  const eventsSeed = [
    {
      title: `Piknik Buku #1 — Lapak Baca di Alun-alun Lumajang`,
      location: `Alun-alun Lumajang, Jl. Alun-alun Utara, Lumajang`,
      dateTime: `2024-02-25T07:00:00+07:00`,
      description: `Kegiatan perdana Majang Buku berupa lapak baca terbuka di Alun-alun Lumajang setiap Minggu pagi. Dengan berbekal tikar and tumpukan buku koleksi pribadi, komunitas ini mengundang siapa saja yang melewati area car free day untuk singgah, membaca, and bertukar cerita. Tersedia puluhan judul buku fiksi and non-fiksi yang bisa dibaca di tempat secara gratis.`,
    },
    {
      title: `Parkir Pikir — Literasi & Kesehatan Mental di Ruang Publik`,
      location: `Alun-alun Lumajang, Lumajang`,
      dateTime: `2024-10-13T07:00:00+07:00`,
      description: `Parkir Pikir adalah event kolaborasi literasi and kesehatan mental pertama di Lumajang yang diinisiasi oleh Majang Buku. Kegiatan ini mengajak peserta untuk berhenti sejenak dari rutinitas, membaca buku, and berdiskusi ringan soal kesehatan mental. Hadir dengan suasana santai and terbuka untuk umum.`,
    },
    {
      title: `Ruang Perempuan Bersuara`,
      location: `Omah Sinau Gesang, Lumajang`,
      dateTime: `2025-04-20T09:00:00+07:00`,
      description: `Ruang Perempuan Bersuara adalah program Majang Buku yang memberikan ruang aman bagi perempuan untuk berbicara, berbagi cerita, and berekspresi melalui buku. Kegiatan ini menghadirkan diskusi buku bertema perempuan, storytelling, and sesi sharing pengalaman personal dalam suasana hangat and mendukung.`,
    },
    {
      title: `Piknik Buku di Alun-alun — Sesi Rutin Minggu Pagi`,
      location: `Alun-alun Lumajang, Lumajang`,
      dateTime: `2025-08-10T07:00:00+07:00`,
      description: `Sesi rutin Piknik Buku di Alun-alun Lumajang setiap Minggu pagi. Komunitas Majang Buku memajang ratusan koleksi buku di atas tikar, terbuka for siapa saja — dari anak-anak hingga dewasa. Pengunjung car free day bisa singgah, membaca, bahkan meminjam buku. Gratis and tanpa syarat.`,
    },
    {
      title: `HUT Majang Buku ke-2: "Hidupkan Lagi Mimpi², Cita², Cinta²"`,
      location: `Oemah Sroedji, Lumajang`,
      dateTime: `2026-02-15T10:00:00+07:00`,
      description: `Perayaan Hari Ulang Tahun kedua Komunitas Literasi Majang Buku yang digelar di Oemah Sroedji, Lumajang. Mengusung tema "Hidupkan Lagi Mimpi², Cita², Cinta²" yang diambil dari penggalan lirik lagu Perahu Kertas, acara ini dihadiri puluhan peserta with dresscode nuansa biru. Rangkaian kegiatan meliputi games literasi, sharing buku, and penulisan harapan di name tag berbentuk perahu kertas.`,
    },
    {
      title: `Piknik Buku #3 Spesial Ramadan — Ngabuburead`,
      location: `Basecamp Majang Buku, Grati – Sumbersuko, Lumajang`,
      dateTime: `2026-03-15T15:30:00+07:00`,
      description: `Piknik Buku spesial edisi Ramadan yang bertajuk "Ngabuburead" — ngabuburit sambil membaca. Kegiatan berlangsung di Basecamp Majang Buku di Grati, Sumbersuko, with agenda pengenalan basecamp, baca senyap, sharing buku bacaan, buka bersama, and tadarus bersama. Tersedia 250+ koleksi buku yang bisa dibaca and dipinjam. Kuota terbatas and peserta wajib konfirmasi terlebih dahulu.`,
    },
    {
      title: `Lebaran Literasi — MBG (Membagikan Buku Gratis) untuk Anak Panti`,
      location: `LKSA Darun Najah, Denok, Lumajang`,
      dateTime: `2026-03-23T09:00:00+07:00`,
      description: `Program sosial Lebaran Literasi yang menyalurkan donasi buku and nominal kepada anak-anak panti asuhan di Kabupaten Lumajang. Periode donasi berlangsung 3–21 Maret 2026, with penyaluran langsung pada 23 Maret 2026 di LKSA Darun Najah, Denok, Lumajang. Kegiatan ini melibatkan volunteer and bertujuan memastikan anak-anak panti turut merasakan kebahagiaan hari raya melalui buku.`,
    },
    {
      title: `Tinta Langit Ramadan Book Festival`,
      location: `Online via Zoom`,
      dateTime: `2026-03-08T10:00:00+07:00`,
      description: `Festival buku online bertema Ramadan yang diselenggarakan dalam tiga sesi: "Ramadan Healing with Books", "Ramadan Reflection with Books", and "Ramadan Growth with Books". Acara berlangsung pada 8 & 14 Maret 2026 via Zoom, masing-masing sesi berdurasi 2 jam. Terbuka for umum and peserta dari luar Lumajang, with pendaftaran melalui PIC yang tersedia.`,
    },
  ]

  for (const event of eventsSeed) {
    await payload.create({
      collection: 'events',
      data: {
        title: event.title,
        location: event.location,
        date: event.dateTime,
        image: null,
        description: {
          root: {
            type: 'root',
            format: '',
            indent: 0,
            version: 1,
            direction: 'ltr',
            children: [
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'text',
                    text: event.description,
                    version: 1,
                  },
                ],
              },
            ],
          },
        },
      },
      req,
    })
  }

  // --- Seed Books ---
  const booksSeed = [
    {
      title: 'Yang Fana Adalah Waktu',
      author: 'Sapardi Djoko Damono',
      isbn_sku: 'KU0002',
      owner_donator: 'Shabila',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Tenggelamnya Kapal Van Der Wijk',
      author: 'Hamka',
      isbn_sku: 'KU0005',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Please Look After Mom',
      author: 'Kyung-Sook Shin',
      isbn_sku: 'KU0006',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Egosentris',
      author: 'Syahid Muhammad',
      isbn_sku: 'KU0009',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Merpati Tak Pernah Ingkar Janji',
      author: 'Mira W.',
      isbn_sku: 'KU0010',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Akhir Kisah Cinta Falcone',
      author: 'Abby Green',
      isbn_sku: 'KU0011',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Perempuan yang Menangis kepada Bulan Hitam',
      author: 'Dian Purnomo',
      isbn_sku: 'KU0012',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Layangan Putus',
      author: 'Mommy Asf',
      isbn_sku: 'KU0014',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Ayat-ayat Cinta',
      author: 'Habiburrahma El Shirazy',
      isbn_sku: 'KU0015',
      owner_donator: 'Rosalia',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Dilan 1990',
      author: 'Pidi Baiq',
      isbn_sku: 'KU0017',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Cinta Tak Pernah Tepat Waktu',
      author: 'Puthut EA',
      isbn_sku: 'KU0019',
      owner_donator: 'Dino',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Kerumunan Terakhir',
      author: 'Okky Madasari',
      isbn_sku: 'KU0022',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Panggil Aku Kartini Saja',
      author: 'Pramoedya Ananta Toer',
      isbn_sku: 'KU0023',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Terangkai Saat Dia Sedang Tidur',
      author: 'Zarry Hendrik',
      isbn_sku: 'KU0029',
      owner_donator: 'Giki Krisnawanti',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Cara Berbahagia Tanpa Kepala',
      author: 'Triskaidekaman',
      isbn_sku: 'KU0030',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Laut Bercerita',
      author: 'Leila S. Chudori',
      isbn_sku: 'KU0031',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Me & Mr. Credit Card',
      author: 'Ardian Yudha',
      isbn_sku: 'KU0035',
      owner_donator: 'Ardian Yudha',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Dilan 1991',
      author: 'Pidi Baiq',
      isbn_sku: 'KU0037',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Aroma Karsa',
      author: 'Dee Lestari',
      isbn_sku: 'KU0038',
      owner_donator: 'Rosalia',
      categories: ['fiksi'],
      status: 'borrowed',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Le Petit Prince',
      author: 'Antoine De Saint',
      isbn_sku: 'KU0039',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'borrowed',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'The Strangers',
      author: 'Albert Camus',
      isbn_sku: 'KU0040',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Lantak La : Dramaturgi Anonim - Anonim',
      author: 'Beri Hanna',
      isbn_sku: 'KU0046',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Menukam Tambo',
      author: 'Beri Hanna',
      isbn_sku: 'KU0047',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'The Power of Language',
      author: 'Shin Do Hyun and Yoon Na Ru',
      isbn_sku: 'KU0048',
      owner_donator: 'Giki Krisnawanti',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Cantik Itu Luka',
      author: 'Eka Kurniawan',
      isbn_sku: 'KU0073',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'borrowed',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Winter In Tokyo',
      author: 'Ilana Tan',
      isbn_sku: 'KU0074',
      owner_donator: 'Rosalia',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Kim Ji-Yeong',
      author: 'Choi Nam Joo',
      isbn_sku: 'KU0075',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Pembunuhan di Nihonbashi',
      author: 'Keigo Higashino',
      isbn_sku: 'KU0076',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Senja, Hujan, and Cerita Yang Telah Usai',
      author: 'Boy Chandra',
      isbn_sku: 'KU0077',
      owner_donator: 'Shabila',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Hujan Bulan Juni',
      author: 'Sapardi Djoko Damono',
      isbn_sku: 'KU0078',
      owner_donator: 'Shabila',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Rectoverso',
      author: 'Dee Lestari',
      isbn_sku: 'KU0079',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'borrowed',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'The Devotion of Suspect X (Kesetiaan Mr. X)',
      author: 'Keigo Higashino',
      isbn_sku: 'KU0080',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'borrowed',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Pingkan Melipat Jarak',
      author: 'Sapardi Djoko Damono',
      isbn_sku: 'KU0081',
      owner_donator: 'Shabila',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Happiness Battle',
      author: 'Joo Youngha',
      isbn_sku: 'KU0082',
      owner_donator: 'Fifi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Pulang',
      author: 'Leila S. Chudori',
      isbn_sku: 'KU0083',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Animal Farm',
      author: 'George Orwell',
      isbn_sku: 'KU0085',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Bumi Cinta',
      author: 'Habiburahman El Shirazy',
      isbn_sku: 'KU0086',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Milea',
      author: 'Pidi Baiq',
      isbn_sku: 'KU0087',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Finn',
      author: 'Honey Dee',
      isbn_sku: 'KU0088',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Critical Eleven',
      author: 'Ika Natassa',
      isbn_sku: 'KU0089',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Black Showman and Pembunuhan di Kota Tak Bernama',
      author: 'Keigo Higashino',
      isbn_sku: 'KU0090',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'borrowed',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Sepotong Senja for Pacarku',
      author: 'Seno Gumira Ajidarma',
      isbn_sku: 'KU0091',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Negeri Para Bedebah',
      author: 'Tere Liye',
      isbn_sku: 'KU0092',
      owner_donator: 'Rosalia',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Sang Patriot',
      author: 'Irma Devita',
      isbn_sku: 'KU0100',
      owner_donator: 'Dafi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Sang Patriot Seri 1: Komik Perjuangan Mempertahankan Kemerdekaan Indonesia',
      author: 'Irma Devita, Aan Budi Sulistyo',
      isbn_sku: 'KU0101',
      owner_donator: 'Dafi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Sang Patriot Seri 2 : Hijrahnya Si Damarwulan',
      author: 'Irma Devita, Aan Budi Sulistyo',
      isbn_sku: 'KU0102',
      owner_donator: 'Dafi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Sang Patriot Seri 3 : Wingate Action',
      author: 'Irma Devita, Aan Budi Sulistyo',
      isbn_sku: 'KU0103',
      owner_donator: 'Dafi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'La Tahzan',
      author: 'Ninit Yunita',
      isbn_sku: 'KU0107',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Tahsin Cinta',
      author: 'DNR Sari',
      isbn_sku: 'KU0110',
      owner_donator: 'Bilik Nulis',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'The Notebook',
      author: 'Nicholas Sparks',
      isbn_sku: 'KU0111',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'The Fault In Our Stars',
      author: 'John Green',
      isbn_sku: 'KU0112',
      owner_donator: 'Rosalia',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Percy Jackson & The Olympians : The Lightning Thief',
      author: 'Rick Riordan',
      isbn_sku: 'KU0114',
      owner_donator: 'Rosalia',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Rendezvous Tiga Hati',
      author: 'Valiant Budi Yogi',
      isbn_sku: 'KU0123',
      owner_donator: 'Diana',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Versus',
      author: 'Ika Natassa',
      isbn_sku: 'KU0124',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Bukan Pasar Malam',
      author: 'Pramoedya Ananta Toer',
      isbn_sku: 'KU0125',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Jakarta Sebelum Pagi',
      author: 'Ziggy zezsyazeoviennazabrizkie',
      isbn_sku: 'KU0126',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Tanpa Rencana',
      author: 'Dee Lestari',
      isbn_sku: 'KU0127',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Emak Ingin Naik Haji',
      author: 'Asma Nadia',
      isbn_sku: 'KU0128',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Love Storm',
      author: 'Clara Canceriana and Feikassy',
      isbn_sku: 'KU0130',
      owner_donator: 'Rak',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'New moon : Dua Cinta',
      author: 'Stephenie Meyer',
      isbn_sku: 'KU0136',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'When Passion Rules (Kembalinya sang Putri Lubinia)',
      author: 'Johanna Lindsey',
      isbn_sku: 'KU0137',
      owner_donator: 'Rosalia',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Rak',
    },
    {
      title: 'Bulan Terbelah di Langit Amerika',
      author: 'Hanum Salsabiela Rais and Rangga Almahendra',
      isbn_sku: 'KU0138',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
    {
      title: 'Reply 1997',
      author: 'Lee Woo Jung',
      isbn_sku: 'KU0141',
      owner_donator: 'Donasi',
      categories: ['fiksi'],
      status: 'available',
      borrowCount: 0,
      bookSource: 'Donasi',
    },
  ]

  for (const book of booksSeed) {
    const categories = book.categories.map((c) => categoryMap[c]).filter(Boolean)
    await payload.create({
      collection: 'books',
      data: {
        title: book.title,
        author: book.author,
        isbn_sku: book.isbn_sku,
        owner_donator: book.owner_donator,
        status: book.status as any,
        borrowCount: book.borrowCount,
        bookSource: book.bookSource as any,
        categories: categories,
        coverImage: null,
      },
      req,
    })
  }
}

export async function down({ payload, req }: MigrateDownArgs): Promise<void> {
  await payload.delete({
    collection: 'books',
    where: { id: { exists: true } },
    req,
  })
  await payload.delete({
    collection: 'faq',
    where: { id: { exists: true } },
    req,
  })
  await payload.delete({
    collection: 'events',
    where: { id: { exists: true } },
    req,
  })
  await payload.delete({
    collection: 'book-categories',
    where: { id: { exists: true } },
    req,
  })
}
